name: signac
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  




dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
